#- hosts: localhost
 # connection: local
  #gather_facts: false
  #roles:
  # - local_inventory

- hosts: workstation
  become: yes
  roles:
    - setup-workstation



- hosts: bastion_tower
  gather_facts: false 
  become: yes 
  roles:
    - install-tower
    - config-tower

