---
# vars file for roles/config-tower
org_name: Default 
scm_branch: master 
scm_url: "https://github.com/prakhar1985/homework-assignment-automation.git"
proj_name: "Homework Assignment"
user_name: admin 
password: r3dh4t1!
ssh_cred_name: "Connect_to_workstation"
user_cred_name: "cloud-user"
user_cred_path: "/root/.ssh/openstack.pem"
static_inventory_name: scm_inventory
job_template_name_osp_infra: osp_infra
instance_group_name: osp
osp_infra_playbook: site-osp-infra.yml
workflow_template_name: cicd_workflow
job_template_name_osp_instances: create-osp-instances
osp_instances_playbook: site-osp-instances.yml
group_name: workstation
host_name: workstation-{{osp_GUID}}.rhpds.opentlc.com
job_template_name_3tier_app: "3tier app deployment"
app_deploy_playbook: site-3tier-app.yml
vault_name: yum_repo_vault
job_template_name_osp_instances_delete: "Delete OSP Instances"
osp_instances_delete_playbook: site-osp-delete.yml
job_template_smoke_osp: "Smoke test QA Env"
osp_smoke_playbook: site-smoke-osp.yml
job_template_aws_provision: "Provision Prod Env"
aws_provision_playbook: aws_provision.yml
ec2_dynamic_inventory: "Three tier inventory"
aws_ssh_playbook: aws_creds.yml
sso_cred_name: "SSO key"
job_template_aws_ssh_keys: "SSH keys three tier app"
ec2_inventory_source: "Three tier inventory source"
aws_read_keys: "AWS Access Keys"
aws_region_name: us-east-1
tag_filters: "tag:instance_filter=three-tier-app-psrivast@redhat.com"
scm_inventory_source: "SCM three tier inventory source"
path_to_scm_inventory: scm_inventory
aws_status_playbook: aws_status_check.yml
job_template_aws_status_check: "Check the status of AWS instances"
job_template_name_3tier_app_aws: "3 tier app on Prod"
aws_cred_name: "Creds for AWS instances"
job_template_smoke_aws: "Smoke test Prod env"
aws_smoke_app_playbook: site-smoketest-aws.yml

